server:
    port: 80
    
spring:
#    resources.static-locations:  classpath:/static/
#    freemarker:
#        prefix: /
#        suffix: .html
    mvc.view:
        prefix: /
        suffix: .html
    jpa:
        hibernate:
            ddl-auto: update
            dialect: org.hibernate.dialect.MySQL5Dialect
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    datasource:
        url: jdbc:mysql://localhost/tracking
        username: root
        password: 
        driver-class-name: com.mysql.jdbc.Driver
    jackson:
        date-format:  yyyy-MM-dd HH:mm:ss
        time-zone: Asia/Kathmandu
        default-property-inclusion: non_null
        serialization:
            INDENT_OUTPUT: false
    mail:
        host: smtp.zoho.com
        username: no-reply@gsewa.com.np
        password: 7fx1Wwe9tF9L
        port: 587
        properties:
            mail.smtp:
                auth: true
                starttls:
                    enable: true
#                    required: true
        transport:
            protocol: smtp
app:
    secret: aeekok5rt4565ythgfbvcd
    expiration: 150000
    header: Authorization
    
fcm.api:
    url: https://fcm.googleapis.com/fcm/send
    key:   AAAAoZWM_y4:APA91bFLbw9blGNym3JycE4J05uZap83-DCYlQYuCRCaGC7F0577BGWKLPf3Fqo-H-QikAcmekcJidn_cjMnHv0am8g2N255ygMKaYShbM58I8PTk2kN4AzNybNXOPn9-2gtfM4MN0UI 
